### ISSUE TITLE
BinaryRequest em ClientSQL dando erro

### ISSUE THREAD

**Issue by mobius1qwe** [OpenSourceCommunityBrasil/REST-DataWare#109]
**Descrição do bug**
> Boa Noite. Quando dou um POST em ClientSQL dá este erro agora nesta versao 2.0:
'{"MESSAGE":"FAIL", "RESULT":"FAIL"}'
> Descobri aqui que com a Propriedade BinaryRequest marcada para TRUE, dá este erro. FALSE passa de boas.

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: 2.0.7
 - IDE: Delphi 11.2
 
 **Relator**
Marcones @freitasmarc

**Comment by freitasmarc** [comment]
Foi feito um teste colocando um novo componente ClientSQL na tela e adicionando os campos, e mesmo assim aparece o erro.

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/ef072327b81be770c65f02114bb7d20d6e4306f0

**Comment by mobius1qwe** [comment]
Aparentemente ainda existe problema com o POST, issue reaberta.

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/f1c877d69768ccabe61edea45cab59b021fdb74c

**Comment by rogeriofrankbras** [comment]
Olá, mesmo após o commit "f1c877d", ao realizar um Post/ApplyUpdates eu recebo um Access Violation, caso esteja com a propriedade BinaryRequest = TRUE (vide imagem). Mas se colocar BinaryRequest = FALSE, grava normalmente.

Plataforma de Teste:
OS: Windows 10 (Build 19045 - 64 bit Edition)
Versão do RDW: 2.0.7 e 2.0.8-29
IDE: Delphi 11.0 Version 28.0.42600.6491
![TELA-AV Gravando Novo Cliente](https://user-images.githubusercontent.com/88019159/236072045-56ab159e-6a3b-43e2-87a1-15a9e4d0767f.jpg)

**Comment by mobius1qwe** [comment]
O commit resolveu o problema lá atrás numa versão que já não é a mais recente. Precisa confirmar o problema em versão recente e abrir uma tarefa se persistir.

**Comment by rogeriofrankbras** [comment]
O teste acima, foi realizado com a Versão  2.0.8-29 do RDW, e o erro persiste.

**Comment by mobius1qwe** [comment]
Certo, confere se o problema ocorre na versão 2.1. Se ocorrer abra uma tarefa nova. Essa tarefa aqui já foi resolvida ano passado.

**Comment by rogeriofrankbras** [comment]
OK, vou fazer isso.
