### ISSUE TITLE
[Bug] UniDac RestDWClientSQL com vários erros

### ISSUE THREAD

**Issue by ElNyko** [OpenSourceCommunityBrasil/REST-DataWare#112]
Quando configuro:
{$ELSE} //Lazarus
 {.$DEFINE RESTDWFHTTP}
 {.$DEFINE RESTDWLAMW} //For LAMW
 {.$DEFINE RESTDWLAZDRIVER}
 {$DEFINE RESTDWUNIDACMEM}
 {.$DEFINE RESTDWMEMTABLE}
{$ENDIF}

Estou utilizando Lazarus 2.2.4 no server e no client. A versão do meu Unidac está em 9.3.0.

Meu server está configurado para utilizar o driver UniDAC. Não encontrei nenhum problema.

Quando vou fazer a conexão em meu Client, e vou utilizar o componente  TRestDwClientSQL com binaryrequest ativo, estou tendo diversos tipos de problemas. Não consigo mais salvar nada. A lista de Fields não salva. Não consigo configurar a máscara para campos do tipo float. Etc....

Não consegui prosseguir com os testes, pois tudo está falhando. Se eu configurar para utilizar RESTDWMEMTABLE, tudo está normal. Não percebi nenhum tipo de problema até agora.

![image](https://user-images.githubusercontent.com/115834515/195932255-1e21aa8e-1f9c-4c23-b807-ccc2f1156c0c.png)

**Informações técnicas:**
 - OS: Microsoft Windows [versão 10.0.19044.2130]
 - Versão do RDW: Version : v2.0.7-3221(Savage Reign - GitHub)
 - IDE: Lazarus 2.2.4

**Comment by mobius1qwe** [comment]
Corrigido no Commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/48887e5826fba2b03b298406c4ebf8305976e2d6
