### ISSUE TITLE
Access Violation Servidor CGI Delphi

### ISSUE THREAD

**Issue by Andersonhrocha** [OpenSourceCommunityBrasil/REST-DataWare#115]
**Descrição do bug**
Ao executar o servidor CGI está dando Access Violation.

**Imagens**
![ERRO CGI](https://user-images.githubusercontent.com/31547202/196696179-3b5206ba-ae30-45eb-95aa-95aca4b7ebad.JPG)

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: 2.0.7 - 3281
 - IDE: 11.2

**Informações Adicionais**
Demo utilizado > 
[CGI DEMO.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/9820619/CGI.DEMO.zip)

**Comment by abritolda1972** [comment]
Com o exemplo não foi possível reproduzir o erro na versão 3285 do sourceforge
sugiro update para a ultima versão ou mais informações sobre o erro.
testado com url /versao
methodo GET

**Comment by Andersonhrocha** [comment]
Atualizei para ultima versão 3285 do sourceforge, e o erro continua, para reproduzir o erro só executar o demo, selecionando a plataforma windows em modo DEBUG.

**Comment by abritolda1972** [comment]
> 

e passa s algum request no modo debug ou vai tudo em branco

**Comment by Andersonhrocha** [comment]
Vai tudo em branco, o erro acontece logo que o servidor é inicializado não chega a rodar, se você tiver algum demo seu rodando normalmente em sua maquina Windows, anexa aqui que baixo para testar no meu ambiente se possível

**Comment by mobius1qwe** [comment]
[CGI DEMO.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/9874564/CGI.DEMO.zip)
Problema no código do seu CGI, segue em anexo o corrigido.
