### ISSUE TITLE
Erro ao dar um post no TRESTDWClientSQL com BinaryRequest ativo.

### ISSUE THREAD

**Issue by RodrigoZanutto** [OpenSourceCommunityBrasil/REST-DataWare#117]
Eu tenho um componente TRESTDWClientSQL, e carrego ele com um "select, select * from cidades inner join regioes", quando eu edito e vou gravar em o erro.
No mapping for the Unico character exists in the target mult-byte code page
e os dados não são gravados.

**Imagens**
Fotos representando o problema se necessário.

**Informações técnicas:**
 - OS: [ex. iOS] Windows
 - Versão do RDW:  Ultima Versão
 - IDE: Delphi Rio

**Comment by RodrigoZanutto** [comment]
Detalhe, não sei se ajuda.
no AfterOpen do client estou usando o seguinte código para mostrar os fileds que não sofrerão alterações.
  DataSet.FindField('cd_codigo').ProviderFlags := [pfInUpdate, pfInWhere, pfInKey];
  DataSet.FindField('rg_identificacao').ProviderFlags := [];

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/f1c877d69768ccabe61edea45cab59b021fdb74c
