### ISSUE TITLE
[Bug] Problema ao abrir com campos InternalCalc e BinaryRequest 

### ISSUE THREAD

**Issue by DelcioSbeghen** [OpenSourceCommunityBrasil/REST-DataWare#131]
**Descrição do bug**
Erro ao abrir o TRESTDWClientSQL(Firedac) caso tenha algum campo InternalCalc, BinaryRequest = True e BinaryCompatibleMode = False 

**Passos para reproduzir o problema**
1. Configure BinaryRequest := True e BinaryCompatibleMode:= False;
2. Adicione um Campo InternalCalc "Teste";
3. Configure Active:= True;
4. Erro: ...Exception class EDatabaseError with message 'RESTDWClientSQL1: Field 'Teste' not found'. Process ...

**Comportamento esperado**
Abrir o Dataset;

**Imagens**
![image](https://user-images.githubusercontent.com/20825422/199025520-1474caf1-d5a6-4688-bb64-994ffe56151a.png)

**Informações técnicas:**
 - OS: [ex. iOS]: Windows 10
 - Versão do RDW: 1.4.3.2775(Killer Instinct)
 - IDE: Delphi 10.4

**Comment by mobius1qwe** [comment]
Versão 1.4.3 não é suportada mais, atualize o seu pacote pra 2.0.7 e, se o erro persistir abra uma nova issue informando o problema.
