### ISSUE TITLE
Problema ao abrir com campos InternalCalc e BinaryRequest

### ISSUE THREAD

**Issue by DelcioSbeghen** [OpenSourceCommunityBrasil/REST-DataWare#132]
**Descrição do bug**
Erro ao abrir o TRESTDWClientSQL(Firedac) caso tenha algum campo InternalCalc, BinaryRequest = True e BinaryCompatibleMode = False 

**Passos para reproduzir o problema**
1. Configure BinaryRequest := True e BinaryCompatibleMode:= False;
2. Adicione um Campo InternalCalc "Teste";
3. Configure Active:= True;
4. Erro: ...Exception class EDatabaseError with message 'RESTDWClientSQL1: Field 'Teste' not found'. Process ...

**Comportamento esperado**
Abrir o Dataset;

**Informações técnicas:**
 - OS: [ex. iOS]: Windows 10
 - Versão do RDW:  v2.0.7-3221(Savage Reign - GitHub)
 - IDE: Delphi 10.4 

#131  Persiste após atualizar o RDW

**Comment by gledstonprego** [comment]
não consegui observar nem simular este erro, criei o campo calculado InternalCalc com adição do campos da tabela com binaryrequest ativo, e uma vez criado o campo InternalCalc obrigatoriamente o dataset passa no evento OnCalcFields onde coloquei a rotina e após select estava incluído no DBGrid com resultado sem ocorrência de erros.

**Comment by mobius1qwe** [comment]
InternalCalc é uma função deprecada, teria que usar o campo calculado pra conseguir funcionar com binary, ou então não usar binary pra usar a função deprecada.
