### ISSUE TITLE
CORS nao funcionando corretamente na nova versão

### ISSUE THREAD

**Issue by leostyles** [OpenSourceCommunityBrasil/REST-DataWare#135]
Na versão antiga o **CORS** respondia de maneira correta, porém ao migrar para a nova versão, mesmo liberando o **CORS** ele insiste em apresentar o erro de permissão...

para reproduzir o problema estou colocando a disposição 2 anexos de html q apontam para um servidor de testes... no primeiro aponta para a versão antiga, e no outro para a nova versão... basta abrir o console do navegador que o erro esta la.

[Link para baixar o HTML](http://pdvsmart.com.br/downloads/erros.rar)

o ambiente do novo servidor é https com o certificado instalado.

outra coisa que notei, se colocar no POSTMAN que é tls1.2 ele da erro também... se remover ele faz a requisição de devolver os dados porem sem resolver o erro de CORS. lembrando que no servidor a opção SSLMethod e SSLVersions esta setada para sslvTLSv1_2.

string do **CORS**

Access-Control-Allow-Origin=*
Access-Control-Allow-Methods=GET, POST, PATCH, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers=Content-Type, Origin, Accept, Authorization, X-CUSTOM-HEADER

e opção **CORS** no componente esta como True

Versao do RDW: 2.0.7-67
Windows 10
Delphi 11 Alexandria

**Comment by mobius1qwe** [comment]
Faltam as informações fundamentais do template:
Versão do RDW 
Sistema operacional
IDE e versão

**Comment by mobius1qwe** [comment]
O problema não pode ser reproduzido no trunk, aparentemente seria problema de TLS entre os servidores, pra isso precisaria usar o pooler da 2.1
