### ISSUE TITLE
[Bug]: MassiveCacheSQL não salva Blobs 

### ISSUE THREAD

**Issue by mobius1qwe** [OpenSourceCommunityBrasil/REST-DataWare#140]
**Descrição do bug**
>Boa tarde pessoal, estou com um problema na hora de salvar a img, na 1.4 estava funcionando agora na 2.0.7 a foto não está salvando, alguém pode me dar uma ajuda?
```Delphi
if imgFoto.Bitmap.Width > 0 then
    begin
      tmpImagem := TBitmap.Create;
      if (imgFoto.Bitmap.Height > 200) or
         (imgFoto.Bitmap.Width > 200) then
         tmpImagem := ReduzirImagem(imgFoto.Bitmap, 200, 200)
      else
         tmpImagem := imgFoto.Bitmap;
      tmpImagem.SaveToStream(tmpStream);
      tmpStream.Position := 0;
    end
    else
    begin
      tmpStream := nil;
    end;

    if imgFoto.Tag = 1 then
    begin
      if tmpStream <> nil then
         vMassiveCacheSQLValue.ParamByName('foto').LoadFromStream(tmpStream, ftBlob)
      else
         vMassiveCacheSQLValue.ParamByName('foto').IsNull;
    end;

    DM.RESTDWDBApp.ProcessMassiveSQLCache(DM.DWMassiveSQLCache01, vError, vMessageError);
```

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: 2.0.7-69
 - IDE: Delphi 10.4

**Relator**
Lemuel Souza

**Comment by DelcioSbeghen** [comment]
Acho que tem haver com a falta de escape das aspas duplas, aqui resolvi alterando em uRESTDWParams.TJSONValue.FormatValue
![image](https://user-images.githubusercontent.com/20825422/202050978-35781310-80af-4062-940d-8ad242253c7f.png)
