### ISSUE TITLE
OpenDatasets não abre corretamente

### ISSUE THREAD

**Issue by Andersonhrocha** [OpenSourceCommunityBrasil/REST-DataWare#145]
**Descrição do bug**
Ao executar um OpenDatasets os dados não estão vindo de forma correta, estou utilizando o Driver Zeos.

**Comportamento esperado**
Ao executar um OpenDatasets trazer os dados corretamente igualmente na versão : v2.0.6-3122

**Imagens**
![image](https://user-images.githubusercontent.com/31547202/202501795-9d7b0942-d263-41b0-8c7f-df4c75f8e92c.png)

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: v.2.0.7-70
 - IDE: Delphi 11.2

**Informações Adicionais**
Segue o Demo utilizado nos testes 
[OPENDATASET DEMO.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10033514/OPENDATASET.DEMO.zip)

**Comment by mobius1qwe** [comment]
manda um demo do server por gentileza com o SQL do banco pra poder testar aqui no SQLite

**Comment by Andersonhrocha** [comment]
Segue o demo do servidor utilizado nos testes
[ServidorVCL-TESTE.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10034240/ServidorVCL-TESTE.zip)

**Comment by mobius1qwe** [comment]
O problema do seu exemplo aí é que você não tá preenchendo todos os parâmetros
`RESTDWIdDatabase.OpenDatasets([QrOpenDataSet], vError, vMessageError);`
se tiver usando binary, teria que ser assim no Zeos:
`RESTDWIdDatabase.OpenDatasets([QrOpenDataSet], vError, vMessageError, true, true);`

desse jeito aí ele abre sem problemas,

**Comment by joseh-henrique** [comment]
Poderia ter um comentário onde é criado o OpenDataset (na origem) sobre isto, assim quando alguém clicar nela para ver a fonte, terá a informação referente a isso, falta isso nos códigos do RestDataWare

**Comment by mobius1qwe** [comment]
Os fontes nunca tiveram documentação no código, é algo que a gente pode implementar no futuro, mas tem prioridade baixa.
