### ISSUE TITLE
[Bug]: Erro compilação android 64

### ISSUE THREAD

**Issue by paulohostert** [OpenSourceCommunityBrasil/REST-DataWare#174]
### Descrição do bug

![image](https://user-images.githubusercontent.com/94071196/212579424-7c7a8a26-86c9-4d2f-87d9-9d928f581ed2.png)

Version : v2.1.0-349(Galaga - SourceForge)

### Passos para reproduzir o problema

Apenas compilar em android 64

### Imagens do problema

![image](https://user-images.githubusercontent.com/94071196/212579508-23576181-9ab6-47a7-a943-c98840e91eb3.png)

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

### Relator do Problema

paulo@phsys.com.br

**Comment by mobius1qwe** [comment]
Corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/7954343a6411180c1deabd9250526d9726065857
