### ISSUE TITLE
[Bug]: Erro compilação IOS Device 64bit 

### ISSUE THREAD

**Issue by paulohostert** [OpenSourceCommunityBrasil/REST-DataWare#184]
### Descrição do bug

Erro na compilação para IOS 64

![image](https://user-images.githubusercontent.com/94071196/215182954-dfc13899-e55c-40b2-a98d-9e3e724aaa67.png)

### Passos para reproduzir o problema

Realizar a compilação para IOS 64.

### Imagens do problema

![image](https://user-images.githubusercontent.com/94071196/215183039-072eb49b-1b12-469a-910e-ce786f1edba8.png)

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

iOS

### Relator do Problema

paulo@phsys.com.br

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/4ccd8a4cd728ea1eedae227f4701037d5bd91642
