### ISSUE TITLE
[Bug]: Erro ao transferir arquivos jpg, pdf, xml via parametro ovBlob

### ISSUE THREAD

**Issue by juniorcsa2022** [OpenSourceCommunityBrasil/REST-DataWare#185]
### Descrição do bug

Na versão 1.43 eu em um único evento retornava 3 arquivos diferentes, jpg, pdf,xml. na versão nova retorna erro.  em anexo segue fontes de exemplo na versão 1.43 e na versão 2.1

[JR_ExemploRDW 2.1-source.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10540417/JR_ExemploRDW.2.1-source.zip)
[JR_ExemploRDW 2.1-EXE.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10540419/JR_ExemploRDW.2.1-EXE.zip)
[JR_ExemploRDW 1.43.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10540422/JR_ExemploRDW.1.43.zip)
[JR_ExemploRDW 1.43-exe.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10540423/JR_ExemploRDW.1.43-exe.zip)

### Passos para reproduzir o problema

Abra o Server, Depois Cliente e clique em buscar arquivos

### Comportamento esperado

Que os arquivos venham corretamente

### Imagens do problema

![image](https://user-images.githubusercontent.com/108020677/215608700-dc46df81-502c-4a57-9c70-d26326efcf9c.png)

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

**Comment by gledstonprego** [comment]
baixei e a principio removi os componentes do cliente, e o pooler do server e coloquei novamente
configurei RESTDWIdClientPooler ativando binaryrequest TRUE, no RIO 10.3
so ajustei as pastas e tudo funcionou tanto com parametros STREAM e BLOB
sempre ativar o binaryrequest TRUE no RESTDWIdClientPooler para a versao 2.1

**Comment by joseh-henrique** [comment]
Poderia pegar os fontes do DFM de ambas (original e corrigida) aqui? Assim eu comparo eles e posto aqui a diferença entre eles, assim dá para saber e ter um roteiro da quebra entre ambos e colocar na Wiki
