### ISSUE TITLE
openjson não lê arquivo maior de 255 caracteres

### ISSUE THREAD

**Issue by EmrysBR** [OpenSourceCommunityBrasil/REST-DataWare#188]
### Descrição do bug

TRESTDWClientSQL.openjson não lê arquivo maior de 255 caracteres,
propriedade Binaryrequest esta True

### Passos para reproduzir o problema

ao executar TRESTDWClientSQL.openjson(MeuJson);

ele retorna o erro:

'Expected a "," or "]" at character 257 of {"id":824173226,"produto_id":156985655,"tabela_preco_id":0,"quantidade":10,"quantidade_grades":[],"preco_tabela":216,"preco_liquido":92.30328,"ipi":0,"tipo_ipi":"P","st":0,"subtotal":923.03,"cotacao_moeda":1,"excluido":false,"descontos_do_vendedor":[57.26":[]} next to : _do_vended' erro no caracter : 257'

### Imagens do problema

![Mercos1](https://user-images.githubusercontent.com/124215271/216189596-ce822c17-a7ba-4609-8c55-1524be91af76.PNG)

### Versão RDW:

2.0.8 (trunk)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

**Comment by EmrysBR** [comment]
atualizei a versão, ele processa mais ao final ele retorna 

Out of memory

![Json1](https://user-images.githubusercontent.com/124215271/216386196-956e6e65-7206-4b2d-9dcb-94761f3dc9dd.PNG)

[Json.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10571227/Json.zip)

**Comment by EmrysBR** [comment]
[Retorno.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/10571279/Retorno.zip)

arquivo json q tento importar

**Comment by mobius1qwe** [comment]
fiz o teste aqui e funcionou assim:
```Delphi
procedure TForm1.Button2Click(Sender: TObject);
begin
  Memo1.Lines.Clear;
  if OpenDialog1.Execute then
    Memo1.Lines.LoadFromFile(OpenDialog1.FileName);
  qyPedidos.OpenJson(Memo1.Lines.Text);
end;
```
O seu código, você define True na propriedade UTF8SpecialChars como visto na imagem:
![image](https://user-images.githubusercontent.com/26689802/216388877-1d1b2246-cdc0-4049-b8d8-14d371bfd192.png)
Essa propriedade só ativa se caso você possuir caracteres não-latinos no JSON e/ou caracteres unicode escapados, por exemplo \u0089.

**Comment by EmrysBR** [comment]
![image](https://user-images.githubusercontent.com/124215271/216392860-e9f278d9-4b1f-4ba7-953c-23d38e20ecb4.png)

o erro acontece quando leio os itens dentro dos pedidos, testei os pedidos sem ler  os itens e funcionou.

**Comment by EmrysBR** [comment]
boa noite

atualizei a versão mais ao ler os itens ele so lê 255 caracteres e retorna o erro de memoria "out of memory"

![mercos3](https://user-images.githubusercontent.com/124215271/217384744-61aff544-0e04-4ac5-988a-ef8f4211850a.PNG)

**Comment by mobius1qwe** [comment]
seu erro não tem a ver com o motivo explicitado na tarefa. 
A tarefa relata problema do ClientSQL.OpenJSON não funcionar por tá com limite de 255 caracteres, fiz o teste no .json que você enviou e ele leu corretamente. Então o problema relatado da tarefa não ocorre.

Seu problema aí é além do simples OpenJSON, ele funciona, seu field do banco que tá capado a 255 caracteres e trunca a string, talvez isso possa ser um erro corrigível pelo RDW, talvez seja algo que você possa resolver modificando os fielddefs, mas não tem nada a ver com o problema inicial da tarefa.
