### ISSUE TITLE
[Bug]: Campo ID vem com valor diferente do que está no BD quando se usa o RESTDWClientSQL

### ISSUE THREAD

**Issue by MrWolfX360** [OpenSourceCommunityBrasil/REST-DataWare#189]
### Descrição do bug

Quando se usa o RESTDWClientSQL com um simples select, o ID deste select vem diferente do que está no banco...

Já utilizando o RESTDWFireDACPhysLink com FDConnection e FDQuery, vem certo!!!

### Passos para reproduzir o problema

Fiz um servidor do zero, utilizando os seguintes componentes:

RESTDWIdServicePooler

um DataModule, contendo RESTDWFireDACDriver, RESTDWFireDACDriver, FDConnection e FDQuery

O banco utilizado é o SQLite, com uma tela clientes, de estrutura simples {id_cliente INTEGER e nome TEXT(40)}

No lado cliente no form tem os seguintes componentes: TDM.RESTDWPoolerDB, RESTDWClientSQL, RESTDWFireDACPhysLink, FDConnection e um FDQuery

no RESTDWClientSQL a SQL é : "select * from clientes", a mesmo no FDQuery 

Quando executado na consulta do FDQuery o ID respeita o que vem do BD, já no RESTDWClientSQL, vem valores diferentes

### Comportamento esperado

Em ambos os componentes, devem vir os mesmo valores, por se tratar da mesma fonte de dados...

### Imagens do problema

![cliente rdw](https://user-images.githubusercontent.com/89548937/216403179-52b8e953-f776-4966-a7d4-7dfc79e8c918.jpg)

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

**Comment by MrWolfX360** [comment]
> Então com a propriedade BinaryRequest ativa o erro não acontece?

Isso mesmo... com essa propriedade ativa, não ocorre !

**Comment by mobius1qwe** [comment]
Na 2.1 o Binary é padrão e vai deixar de ser opcional nas próximas versões, vai ficar embutido nos componentes.
