### ISSUE TITLE
[Bug]: RESTClientPooler não executando os eventos Work, WorkBegin e WorkEnd na versão 2.1

### ISSUE THREAD

**Issue by paulohostert** [OpenSourceCommunityBrasil/REST-DataWare#200]
### Descrição do bug

No componente RESTClientPooler, os eventos Work, WorkBegin e WorkEnd não estão sendo chamados na versão 2.1.

A proriedade AWorkMode, também não está mais disponível.

### Passos para reproduzir o problema

Atribuir eventos OnWork, workbegin e eworkend ao componente RESTClientPooler e realizar a depuração. Acredito que os mesmo não estão sendo cahamados.

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

### Relator do Problema

paulo@phsys.com.br

**Comment by mobius1qwe** [comment]
Corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/c16ab0aac3b176177f6ab7f2d3f57aa9b3b606cf
