### ISSUE TITLE
[Bug]: Erro de acentuação com FireDACPhysLink FMX

### ISSUE THREAD

**Issue by jhonwilker** [OpenSourceCommunityBrasil/REST-DataWare#215]
### Descrição do bug

quando executo a query para trazer os dados do banco eles não vem com acentos.
banco postgres, versão 2.1 cliente FMX usando FireDACPhysLink

### Passos para reproduzir o problema

criar um projeto com o banco de dados postgres , dados com acentos , cliente fmx  servidor vcl.

### Comportamento esperado

acentos quando tudo selecionado padrão utf8

### Imagens do problema

![WhatsApp Image 2023-02-15 at 22 18 10](https://user-images.githubusercontent.com/37003706/219235836-ada23ce3-e344-4054-904f-a63f5b6774fd.jpeg)

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

### Relator do Problema

jhonwilker

**Comment by jhonwilker** [comment]
alterando a propriedade binary request foi resolvido o problema

**Comment by mobius1qwe** [comment]
Reabrindo tarefa pois precisa funcionar com BinaryRequest ativo.

**Comment by mobius1qwe** [comment]
problema não ocorre na última versão da 2.1
