### ISSUE TITLE
[Bug]: Problemas com binary e ClientSQL no Windows para campos BCD

### ISSUE THREAD

**Issue by lassistemas** [OpenSourceCommunityBrasil/REST-DataWare#222]
### Descrição do bug

Problemas com o RESTDWClientSQL ambiente Windows.

-  BinaryRequest ativado:
   - Quando um campo é tipo NUMERIC e a escala é maior que 3, exemplo `NUMERIC(13,4)` apresenta o erro: "BCD overflow" 
da **imagem 1**

- BinaryRequest ativo ou não:
  - Quando adiciona um campo é tipo FLOAT usando o Field Editor (Campo vem direto do BD) apresenta o erro: "NOME DA TABELA filed NOME DO CAMPO is of unknown  type": **Imagem 2**

- BinaryRequest desativado:
   - Quando tem campo OBRIGATÓRIO e tenta abrir a tabela. **Imagem 3**

### Passos para reproduzir o problema

Usando o Field Editor do RESTDWClientSQL

### Comportamento esperado

Deveria vir todos os campos sem nenhum ou modificação de valor (caso BCD overflow)

### Imagens do problema

<details>
<summary>Imagem 1</summary>
<img src="https://user-images.githubusercontent.com/102775670/220352434-c2b31f83-bbea-4908-b112-3312da93d561.jpg" />
</details>
<details>
<summary>Imagem 2</summary>
<img src="https://user-images.githubusercontent.com/102775670/220349977-aa17a3f2-0b02-471e-9398-2c2a19df39a3.png" />
</details> 
<details>
<summary>Imagem 3</summary>
<img src="https://user-images.githubusercontent.com/102775670/220354346-3fb9b459-c5ff-489f-b742-9701262bbb72.png" />
</details> 

### Versão RDW:

2.1.0 (branch)

### IDE:

Delphi novo

### Sistema Operacional:

Windows

**Comment by mobius1qwe** [comment]
Você tá usando uma versão antiga, com release code 371. Sugiro atualizar pra última versão disponível e testar pra ver se o erro persiste. Se não persistir avise pra fechar a tarefa.

**Comment by lassistemas** [comment]
Boa tarde,

Desde agradeço o retorno, me desculpe mais não estou achando a release mais nova, esse que tenho baixei a semana passada

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lassistemas** [comment]
Vou atualizar agora
________________________________
De: Mobius One ***@***.***>
Enviado: quinta-feira, 23 de fevereiro de 2023 22:35
Para: OpenSourceCommunityBrasil/REST-DataWare ***@***.***>
Cc: LAS-Sistemas ***@***.***>; Author ***@***.***>
Assunto: Re: [OpenSourceCommunityBrasil/REST-DataWare] [Bug]: Problemas com binary e ClientSQL no Windows para campos BCD (Issue #222)


Você tá usando uma versão antiga, com release code 371. Sugiro atualizar pra última versão disponível e testar pra ver se o erro persiste. Se não persistir avise pra fechar a tarefa.

**Comment by lassistemas** [comment]
Bom dia Mobius,

Com a nova versão resolveu o problema, mas, agora está dando memory leak no open do RESTDWClientSQL
________________________________
De: Mobius One ***@***.***>
Enviado: quinta-feira, 23 de fevereiro de 2023 22:35
Para: OpenSourceCommunityBrasil/REST-DataWare ***@***.***>
Cc: LAS-Sistemas ***@***.***>; Author ***@***.***>
Assunto: Re: [OpenSourceCommunityBrasil/REST-DataWare] [Bug]: Problemas com binary e ClientSQL no Windows para campos BCD (Issue #222)


Você tá usando uma versão antiga, com release code 371. Sugiro atualizar pra última versão disponível e testar pra ver se o erro persiste. Se não persistir avise pra fechar a tarefa.

**Comment by mobius1qwe** [comment]
Certo, leak é outro problema. Procure uma forma precisa de repetir o leak e abra uma nova tarefa com os detalhes pra reproduzir que a gente arruma.

**Comment by lassistemas** [comment]
Usei o MadExcetion para verificar aonde estava o problema e apareceu o seguinte:

[cid:d3318049-5f93-4ebb-b09b-7491ea9f57ff]
no meu sistema a linha do problema é um OPEN do RestDWClientSQL, notei que o problema é quando no Select tem um campo BLOB
________________________________
De: Mobius One ***@***.***>
Enviado: sexta-feira, 24 de fevereiro de 2023 12:33
Para: OpenSourceCommunityBrasil/REST-DataWare ***@***.***>
Cc: LAS-Sistemas ***@***.***>; Author ***@***.***>
Assunto: Re: [OpenSourceCommunityBrasil/REST-DataWare] [Bug]: Problemas com binary e ClientSQL no Windows para campos BCD (Issue #222)


Certo, leak é outro problema. Procure uma forma precisa de repetir o leak e abra uma nova tarefa com os detalhes pra reproduzir que a gente arruma.
