### ISSUE TITLE
[Bug]: Desempenho do PhysLink 

### ISSUE THREAD

**Issue by nildglan** [OpenSourceCommunityBrasil/REST-DataWare#255]
### Descrição do bug

sobre PhysLink testei em uma aplicação minha com firedac, mais o desempenho foi ruim, quando se trata de querys qye envolve join e ligações com  outras tabelas e volume de dados não deu pra trabalhar

### Passos para reproduzir o problema

fiz os testes na minha aplicação em produção

### Versão REST DataWare:

2.1.0 (branch)

### IDE:

Delphi 10+

### Sistema Operacional:

Windows

**Comment by mobius1qwe** [comment]
Quais os erros? Quais os problemas? Qual o ponto que fica lento? Fazendo o quê? Precisa ser mais descritivo, só isso daí não dá pra ter um ponto de partida pra corrigir algo.
