### ISSUE TITLE
[Bug]: Propriedade NeedAuthorization não funciona como deveria

### ISSUE THREAD

**Issue by eloysge** [OpenSourceCommunityBrasil/REST-DataWare#273]
### Descrição do bug

A propriedade NeedAuthorization não está sendo levado em consideração na execução do evento.
Se a props estiver como false, nas chamadas internas do evento (não pelo browse ou postman), também está sendo requerido a autenticação.

### Passos para reproduzir o problema

NULL

### Versão REST DataWare:

2.1.0 (branch)

### IDE:

Delphi 10+

### Sistema Operacional:

Windows

**Comment by mobius1qwe** [comment]
corrigido no PR #300
