### ISSUE TITLE
[Bug]: Erro instalação Delphi 12, DBtables not found

### ISSUE THREAD

**Issue by paulohostert** [OpenSourceCommunityBrasil/REST-DataWare#368]
### Descrição do bug

Na compilação dos pacotes para o delphi 12 ocorre o erro:
[dcc32 Fatal Error] uRESTDWProtoTypes.pas(29): F2613 Unit 'DbTables' not found.

### Passos para reproduzir o problema

Instalação RDW no Delphi 12.
Build no pacote RESTDWCore.bpl

### Imagens do problema

![image](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/assets/94071196/63a42f5b-4a8d-456f-a7b9-4f5b82964b57)

### Versão REST DataWare:

2.1.0 (branch)

### IDE:

Delphi 10+

### Sistema Operacional:

Windows

**Comment by gledstonprego** [comment]
certifique-se de colocar todas as pasta e subpastas da source do componente

**Comment by paulohostert** [comment]
Estou utilizando a mesma pasta de instalação do Delphi 11


Paulo Hostert

Em ter., 5 de set. de 2023 21:15, gledstonprego ***@***.***>
escreveu:

**Comment by Ronierys2** [comment]
@paulohostert 

baixe a versão atualizada do repositório, todos os testes de instalação do Delphi 12 foram feitos.
atualmente estou usando o Delphi 12 tanto para desenvolver o RestDataware, quanto para os testes e a instalação esta 100%, houveram ajustes de compatibilidade que já foram corrigidos.
