### ISSUE TITLE
[Bug]: Erro instalação pacote RESTDWSocketIcs com Delphi 12

### ISSUE THREAD

**Issue by paulohostert** [OpenSourceCommunityBrasil/REST-DataWare#375]
### Descrição do bug

No build do pacote RESTDWSocketIcs ocorre o erro:

[dcc32 Fatal Error] RESTDWSocketIcs.dpk(35): E2202 Required package 'OverbyteIcsD110Run' not found

### Passos para reproduzir o problema

Build no pacote RESTDWSocketIcs.

### Imagens do problema

![image](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/assets/94071196/3b6c04aa-e275-4bc0-82e6-3b643ca08f23)

### Versão REST DataWare:

2.1.0 (branch)

### IDE:

Delphi 10+

### Sistema Operacional:

Windows

### Relator do Problema

paulo@phsys.com.br

**Comment by gledstonprego** [comment]
o socketICS do RDW precisa do componente OverbyteICS instalado previamente, só depois compila e instala o pacote RDW
