### ISSUE TITLE
[Bug]: Missing uRESTDWMemtable.pas 

### ISSUE THREAD

**Issue by jstb24** [OpenSourceCommunityBrasil/REST-DataWare#376]
### Descrição do bug

Trying installation for Delphi 11 can not compile the Databasedriver UniDAC because the uRESTDWMemtable.pas missing.

Tentando a instalação para Delphi 11 não é possível compilar o Databasedriver UniDAC porque o uRESTDWMemtable.pas falta.

### Passos para reproduzir o problema

1. open Package
2. clean+compile
3. [F2613] Unit uRESTDWMemtable not found

### Versão REST DataWare:

2.1.0 (branch)

### IDE:

Delphi 10+

### Sistema Operacional:

Windows

**Comment by gledstonprego** [comment]
you need to put all the source folders and subfolders in the delphi path, to install the RDW drivers you have to have the components installed Unidac, Zeos and others that you are going to use first install the components then the RDW Drivers during the installation of the software packages RDW, before creating an issue, ask the group about questions about installing RDW.
