### ISSUE TITLE
[Bug]: Rest dataware do not compile on FPC 3.2.3 fixes

### ISSUE THREAD

**Issue by ucuccen** [OpenSourceCommunityBrasil/REST-DataWare#377]
### Descrição do bug

Hello.
For information RDW do not compile on FPC3.2.3 fixes.

### Passos para reproduzir o problema
The supported datatypes in fpc3.2.3 is equivalent to fp 3.3.1 and delphi.
Error messages 
uRESTDWDataset.pas(884,14) Note: Virtual method "SetFieldData(TField;Pointer);" has a lower visibility (protected) than parent class TDataSet (public)
uRESTDWDataset.pas(1046,14) Note: Virtual method "Loaded;" has a lower visibility (protected) than parent class TRESTDWCustomDataSet (public)
uRESTDWDataset.pas(1152,59) Error: Expected another 7 array elements

### Imagens do problema
![image](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/assets/94351324/d9fcfedb-7ae3-4e37-b305-2611c64d2e6e)

_No response_

### Versão REST DataWare:

2.0.7 (latest release)

### IDE:

Lazarus

### Sistema Operacional:

Windows

**Comment by gledstonprego** [comment]
only the current version 2.1 alpha is supported, no version below is supported and will not have bugs fixed.

**Comment by ucuccen** [comment]
Another thing, The wizzard for new project do not appear on the new project form.
(template for new project does not exists )

![image](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/assets/94351324/9d1db0f9-95cb-45ee-8193-c51bed2e749b)

**Comment by gledstonprego** [comment]
Please use the group to post questions, this is not the right place, and the wizard is not complete

**Comment by ucuccen** [comment]
I think that RestDataware is a good product, but It leak complete support for lazarus ( clean simples to show different functionnalities ).
I spend a whole day and I did not success building a CGI application.
Good luck.
I'll continue my work with native CGI lazarus support.

Thank you.

**Comment by acgubamg** [comment]
Delphi12 acontece isso tambem
