### ISSUE TITLE
[Bug] 404 ao usar binary request

### ISSUE THREAD

**Issue by GuilhermeDischer** [OpenSourceCommunityBrasil/REST-DataWare#42]
**Descrição do bug**
O erro ocorre ao usar binary request para trafegar um dataset.
Se eu passar a rota sem parametro ocorre um AV(No Server).
Se eu passar o parametro é retornado 404.

**Comportamento esperado**
Retornar os Dados para passar para uma Query

**Imagens**
![image](https://user-images.githubusercontent.com/73898413/185233513-fbe7cde4-8818-4b0d-87f0-15894ec7d93d.png)
Como é feito a requisição

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: v2.0.0-3054(Savage Reign - Source Forge)
 - Plataforma de destino de compilação: Windows

**Informações Adicionais**
Estou usando Delphi VCL

**Comment by mobius1qwe** [comment]
Corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/aea70f687a4f7c9065ad9a7a69c23a7983b5db64
