### ISSUE TITLE
[Bug] Abstract Error - RESTDWClientSQL

### ISSUE THREAD

**Issue by Andersonhrocha** [OpenSourceCommunityBrasil/REST-DataWare#43]
**Descrição do bug**
Ao tentar inserir dados na tabela utlizando o RESTDWClientSQL.ExecSQL está dando um erro Abstract Error e não inseri nada na tabela. 

**Comportamento esperado**
Ao executar RESTDWClientSQL.ExecSQL inserir normalmente o dado na tabela como na versão anterior que está funcionando perfeitamente. 

**Imagens**
![image](https://user-images.githubusercontent.com/31547202/185238092-a533f253-ab29-448f-900a-2d7b6380ad8b.png)

**Linha com o erro**
![image](https://user-images.githubusercontent.com/31547202/185238551-b0bdeee3-6a59-46b0-b609-b05bf8544077.png)

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: v2.0.0-3064(Savage Reign - Source Forge) 
 - Plataforma de destino de compilação: Windows 

**Informações Adicionais**
Estou usando Delphi 10.4.2 VCL

**Comment by mobius1qwe** [comment]
Por gentileza confirme se o erro persiste ou se já foi resolvido.

**Comment by Andersonhrocha** [comment]
Acabei de atualizar o pacote e o erro ainda continua

**Comment by mobius1qwe** [comment]
Poderia informar as configurações das propriedades do seu ClientSQL e do DWIdDataBase por gentileza? Pra poder reproduzir o problema aqui.

**Comment by mobius1qwe** [comment]
Corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/163a6472eda03f2f7321d027c4664a52a606a678
