### ISSUE TITLE
Campo Data e hora inválido com BinaryRequest = true

### ISSUE THREAD

**Issue by tatianepeixoto** [OpenSourceCommunityBrasil/REST-DataWare#65]
Com RESTDWClientSQL_Gru.BinaryRequest  := **true** tras os dados DATA e HORA zerados no grid conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/81206006/187534312-fbfbc757-87e7-45d4-8984-825b08648b85.png)

Para que traga as campos DATA E HORA no grid corretamente sou obrigada usar BinaryRequest  do RestDWClient como FALSE, dai tras os dados corretamente.

![image](https://user-images.githubusercontent.com/81206006/187534533-3bf5a67e-d4fe-46d0-99ac-e03695dd7673.png)

![image](https://user-images.githubusercontent.com/81206006/187534767-bf5f878b-244b-4471-8fa8-95ef047a01f9.png)

**Informações técnicas:**
 - OS: Windows 10
 - Versão do RDW: Version : v2.1.0-3103(Galaga - GitHub)
 - IDE: Lazarus 2.0.10

**Comment by mobius1qwe** [comment]
Corrigido no commit: https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/aac291b06fde8f0fa56de0e6a9307679b95bbb11

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/ef072327b81be770c65f02114bb7d20d6e4306f0
