### ISSUE TITLE
[Bug] Erro ao compilar para FMX

### ISSUE THREAD

**Issue by lassistemas** [OpenSourceCommunityBrasil/REST-DataWare#67]
Quando compilo para FMX aparece seguinte err:
uRESTDWParams.pas(1569): E2003 Undeclared identifier: 'TDWJSONArrayType'

 - OS: android
 - Versão do RDW: 2.05
 - IDE: Delphi
![Sem título](https://user-images.githubusercontent.com/102775670/187819144-631318b6-2a4d-4bf5-b5b8-3df8cb884a51.png)

**Comment by mobius1qwe** [comment]
Corrigido  no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/f7e1565eaac3a7202dcb9d698b211886ee9f259e
