### ISSUE TITLE
A função FailOverConnections não está chamando o evento GetToken

### ISSUE THREAD

**Issue by delmardelima** [OpenSourceCommunityBrasil/REST-DataWare#82]
**Descrição do problema**
O evento GetToken esta funcionado no servidor principal(IP), mas caso o mesmo estiver indisponível, o segundo servidor(IP) só responde as requisições caso informar o Token Bearer gerado manualmente, não chamando o evento GetToken no componente: TRESTDWIdClientPooler.

**Imagens**
<details>
  <summary> Imagens </summary>
<img src="https://user-images.githubusercontent.com/27692608/190232746-85cc456e-e80a-4923-ae3f-ca072ff1ca1a.jpg"/>
<img src="https://user-images.githubusercontent.com/27692608/190232754-8dd12e5c-3119-48bf-85bc-1a4b3fa18242.jpg"/>
<img src="https://user-images.githubusercontent.com/27692608/190232756-011771d4-aa8a-4372-9c55-02e5774aa89d.jpg"/>
</details>

OS: Windows
Versão: v2.0.6-3127(SavageReign - SourceForge)
IDE: Delphi 10.4

**Comment by mobius1qwe** [comment]
corrigido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/e54cc5ecb3e393675bf3fb15d9ef9aca4e390e1b
