### ISSUE TITLE
AV em CGI Delphi

### ISSUE THREAD

**Issue by Andersonhrocha** [OpenSourceCommunityBrasil/REST-DataWare#83]
**Descrição do bug**
Ao executar um chamado no ShellService, ocorre um AV e para na linha 230 da unit uRESTDWShellServicesDelphi.

**Imagem**
![image](https://user-images.githubusercontent.com/31547202/190639068-4609e291-42da-4ed9-a7d0-9720e2d70338.png)

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: 2.0.6 - 3182
 - IDE: Delphi 10.4.2

**Informações Adicionais**
Demo utilizado no teste
[Demo CGI.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/9583967/Demo.CGI.zip)

**Comment by abritolda** [comment]
AV não confirmado, não foi possível reproduzir o erro fazer update para a ultima versão

**Comment by mobius1qwe** [comment]
Encerrando a tarefa pois não foi possível confirmar o erro.
