### ISSUE TITLE
Abstract Error OpenDatasets Delphi

### ISSUE THREAD

**Issue by Andersonhrocha** [OpenSourceCommunityBrasil/REST-DataWare#84]
**Descrição do bug**
Ao executar um OpenDatasets utilizando o RESTDWClientSQL está dando Abstract Error.

**Imagens**
![image](https://user-images.githubusercontent.com/31547202/190643028-fad16f84-f15f-4d57-a551-38d31305668a.png)

**Informações técnicas:**
 - OS: Windows
 - Versão do RDW: 2.0.6 - 3182
 - IDE: 10.4.2

**Informações Adicionais**
Servidor utilizado RDWDemos > Delphi\VCL\FullServer

Anexo do cliente para testar
[Demo RESTDWClientSQL.zip](https://github.com/OpenSourceCommunityBrasil/REST-DataWare/files/9584155/Demo.RESTDWClientSQL.zip)

**Comment by Andersonhrocha** [comment]
Novo teste do OpenDataSet realizado no commit v2.0.7 - 3280 não está mais dando o abstract Error só que não estar trazendo os dados corretamente, foram compilado servidor e cliente na mesma versão.

![OpenDataSet Erro](https://user-images.githubusercontent.com/31547202/196712131-73078245-a741-42bf-ac10-6f29006da178.jpg)

**Comment by mobius1qwe** [comment]
Confere por gentileza se com o último commit 24/10/2022 o erro persiste, se persistir abra uma outra Issue do problema, por gentileza, já que não é mais o mesmo erro do tópico da tarefa.
