### ISSUE TITLE
O Evento GetToken não funciona em Maquinas Remotas

### ISSUE THREAD

**Issue by delmardelima** [OpenSourceCommunityBrasil/REST-DataWare#88]
**Descrição do bug**
O componente TRESTDWIdDatabase ao enviar o evento GetToken, está ignorando o IP Remoto passado no paramento PoolerService e Enviando o evento GetToken para LocalHost, conforme imagem logo abaixo.

**Passos para reproduzir o problema**
1. Vá para o componente TRESTDWClientSQL, abre uma tabela "select * from tabela" em modo runtime
2. Erro irá aparecer em modo Debug no TRESTDWClientSQL.Open

**Imagens**
<details>
  <summary>Imagem 1</summary>
 <img src="https://user-images.githubusercontent.com/27692608/191350084-3206811d-6c1c-43b5-8502-f9fc16378eab.jpg"/>
</details>
<details>
  <summary>Imagem 2</summary>
 <img src="https://user-images.githubusercontent.com/27692608/191350090-5d063219-c5bb-4e4a-bedf-2b30c638ac8b.jpg" />
</details>
<details>
  <summary>Imagem 3</summary>
 <img src="https://user-images.githubusercontent.com/27692608/191350096-819d2118-3627-49c1-9a33-dc372813a8e2.jpg" />
</details>

**Informações técnicas:**
 - OS: Windows 10
 - Versão do RDW: Version : v2.0.6-3127(Savage Reign - GitHub)
 - IDE: Delphi 10.4

**Informações Adicionais**
Conforme contato pelo Telegram do componente.

**Comment by delmardelima** [comment]
a Function TRESTDWPoolerMethodClient.GetToken localizada na unit uRESTDWPoolermethod não esta configurando o componente RESTClientPoolerExec, conforme as outras funções da mesma unit. Não configura Host, Port, etc... resolvir o problema momentanio alterando na unit uRESTDWBasic o localhost para o IP remoto.
![image](https://user-images.githubusercontent.com/27692608/191654134-da35d9f5-93cb-456a-a27b-ec1adb58a14f.png)
![image](https://user-images.githubusercontent.com/27692608/191654177-45a12c7f-f7ec-4010-98d8-c4d1bafb98d0.png)

**Comment by mobius1qwe** [comment]
resolvido no commit https://github.com/OpenSourceCommunityBrasil/REST-DataWare/commit/e54cc5ecb3e393675bf3fb15d9ef9aca4e390e1b
