### ISSUE TITLE
erro de compilacao delphi xe2 no restdwsocketindy

### ISSUE THREAD

**Issue by gabriellc** [OpenSourceCommunityBrasil/REST-DataWare#92]
**Descrição do bug**
[DCC Error] uRESTDWIdBase.pas(2252): E2003 Undeclared identifier: 'Id_HTTPMethodPatch'

**Passos para reproduzir o problema**
nao compilacao do uRESTDWIdBase.pas, da esse erro em algumas linhas.

**Comment by mobius1qwe** [comment]
Primeiro, garanta que você seguiu todos os passos aqui: https://github.com/OpenSourceCommunityBrasil/REST-DataWare/wiki/Instala%C3%A7%C3%A3o

Em seguida, garanta que você esteja utilizando a última versão do repositório. Se o erro persistir, abra uma issue seguindo todas as informações do template que são necessárias pra que a gente consiga reproduzir o problema pra conseguir resolver.
