### ISSUE TITLE
[Bug] DWDataModule buscando Eventos do ServerEvents em LowerCase

### ISSUE THREAD

**Issue by FernandoBanhos** [OpenSourceCommunityBrasil/REST-DataWare#95]
Ao acionarmos um evento o mesmo somente será encontrado se a URL estiver com letras minúsculas

**Passos para reproduzir o problema**
1. Crie um evento (ex: buscarCliente)
2. Vá no Browse e busque a URL: http://localhost:8082/buscarCliente
4. O evento não será encontrado (erro: Event not Found)

Vi que na unit uDWRestDatamodule, linha 237 está assim: 
 vTempValue := URL;
 
 já nas linhas 248 e 292 esta assim
 vTempRoute := Lowercase(TRESTDWServerEvents(Components[I]).Events[A].BaseURL   +
                          TRESTDWServerEvents(Components[I]).Events[A].EventName);
                          
logo se deduz que a URL deveria ser LowerCase, trocando a linha 237 para:
 vTempValue := LowerCase(URL);                          
 
Mas, ouvi comentários que o RDW estaria tratando os eventos como case-sensitive, logo a maneira de resolver seria outra
Por hora resolvi nos meus fontes dessa maneira...

**Comment by mobius1qwe** [comment]
O problema aí de setar lowercase(URL) é que você joga toda a URL pra minúsculo, sendo que os parâmetros precisam ser case-sensitive, só os eventos que são insensitive. Daí num seria tão simples assim só jogar tudo pra minúsculo, teria que isolar o evento que hoje possui uma BaseURL variável pra somente ele ser setado como minúsculo.

**Comment by FernandoBanhos** [comment]
bem simples intao... usar comparetext ou sametext no momento da comparacao...
